# (PART) Data Access and Preparation {-}

# WP-2 - Data Cleaning

```{block, type = "rmdgoal"}
**Goal:** Create main analysis data sets for mapping.
```

```{block, type = "rmdpersonnel"}
**Personnel:** This waypoint should be completed by **all** students. 
```

```{block, type = "rmdskills"}
**Skills:** This waypoint requires skills from both Module 1 and 2
```

```{block, type = "rmddue"}
**Due Date:** Meeting 3-1 (February 28th)
```

```{block, type = "rmddeliver"}
**Deliverables:** A well organized project repository with an appropriate folder structure, a plan implemented with GitHub Projects, a `README.md`, a `RESEARCH_LOG.md`, and a `.Rproj` file. These should all be *created* by the due date, but will continue to be updated afterwards. You will also need a well-formatted notebook in the `docs/` folder that uses literate programming to produce a clean data set saved as a `.csv` file in the `data/` folder.
```

## Data Storage
You will have a separate GitHub repository that is dedicated to the final project. This will facilitate some of the peer evaluation tasks you will be asked to complete over the course of the semester, allowing you to share a repository with a colleague without exposing all of your other work and grades in the process. 

All final project materials should be stored in this repository, and it should be organized following the [project organization principles we've used this semester](https://slu-soc5650.github.io/docs/protecting-work/). This means that it should have subfolders for `data/`, `docs/`, `results/`, and `source/` as well as a `.Rproj` file.

If subfolders are empty, they will not be tracked by GitHub. If you are using only one computer, the folder will remain visible locally and Git will start tracking it once you begin adding materials. If you are using multiple computers, you can create empty text files named `.gitkeep` using RStudio (`File > New File > Text File`) and keep one in each subfolder.

Since you will be storing this repository on GitHub, you will be default be using version control for this project. You should make commits (like voting in Chicago!) early and often. Make sure that your commit messages are informative and clear. Remember, if you have to go back to an earlier version of your work, you will want to make it as easy as possible to do so.

Also make sure that you are pushing to GitHub often and not just saving the work locally on your computer. This is *part* of your insurance against a catastrophic loss of your computer or a lab computer where you are working. You are strongly encouraged to use a more comprehensive backup solution!

## Project Planning
Use GitHub’s "Project Board" feature on your final project's GitHub repository to plan out the tasks you need to complete. Create a new project and assign each waypoint to a column. Then assign specific tasks and deliverables related to that waypoint to individual notes in that column. As you progress through the project, keep this updated so that you can track your progress. You can read more about [managing projects](https://help.github.com/articles/managing-project-boards-in-your-repository-or-organization/) and [tracking progress with a project board](https://help.github.com/articles/tracking-the-progress-of-your-work-with-project-boards/) in GitHub's documentation.

## Project Documentation
There are two project-level documentation files that you will need to create and keep updated throughout the semester.

### README.md
You will need a read-me file in the top-level of your assignment repository. There will already be a file named `README.md` in the top-level of your repository. Please edit this and modify it as needed!

### RESEARCH_LOG.md
You will need to maintain a research log throughout the final project process. Before proceeding with the waypoints, create a well-formatted and organized research log in RStudio (`File > New File > Text File`) that is organized chronologically. The research log should use markdown syntax and be saved as a markdown file (`.md`). Keep this file updated and have it saved in the top-level of your assignment repository.

For each day you work on the final project, there should be an entry that describes the work that you have done, what files you have created or modified, and how those modifications took place. Give as much detail as possible without directly replicating the notes you make in individual files using the literate programming approach. This will be particularly important for your mapmaking work in ArcGIS Pro, which is inherently not reproducible and thus good notes are imperative.

Think of the research log as step-by-step instructions to yourself that would allow you to recreate all of your work should every final project file you work on be accidentally deleted or lost. For code, you can provide higher level details since, ideally, your literate programming approach means that your code is well annotated and described. For plots and your slides, you want to provide as much fine grained detail as possible down to specific font, color, and size choices for data and layout elements.

## Data Cleaning Overview

### Analysis Development

All data cleaning should be done in a single notebook that you clarify and expand over time. Use `dplyr`, `naniar`, `janitor`, and `sf` for data cleaning in short, well-organized pipelines.

### General Approach

The amount of data cleaning needed will vary significantly based on the data set you are using and the measures you have selected. Thus there are no "one size fits all" instructions for cleaning your data, though you should follow the [data cleaning workflow](https://github.com/slu-soc5650/module-2-data-cleaning/blob/master/handouts/wranglingWorkflow.pdf) we discussed in class. In general, you will want to focus on making sure a number of criteria are met:

1. Variables should have short, clear, intuitive names.
2. All missing data have been recoded to `NA` values (if they were not already coded that way).
3. If your data set does not include identification numbers for each row, you will need to create them. The `tibble` package's [`rowid_to_column()`](https://tibble.tidyverse.org/reference/rownames.html) function can be used for this.
4. Only columns necessary for mapping should be included - subset out all other columns.
5. Only observations necessary for mapping should be included - subset out all other observations (i.e. if you are using the crime data, subset out all crimes not in the category you are working with). You will also want to remove all duplicate observations.
6. Identify and subset out data missing spatial references. In the crime data set, these will either be missing already (`NA` values) or have values of `0`. In the CSB data set, these will either be missing already (`NA` values) or have values less than `800000` in the `x` coordinate and less than `980000` in the `y` coordinate.
    * If you are using another data source, make sure there are no missing data. The indicators above are similar to the indicators you should look for.
7. Remove observations in the crime data where the count is `-1` and in the CSB data where there is a stats of `CANCEL`. 
    * If you are using another data, make sure there are no observations for invalid data, as in calls for service that were canceled or crimes that were removed from the data set.
8. Clean and modify the values of specific observations as needed. 
    * For example if you have a category variable - which both the crime and CSB data do, make sure it returns short, clear values. If you have multiple categories in such a variable, create a new categorical variable that simply differentiates between the relevant codes. For instance, the following values are the focus of a sample project using the CSB data. These nine categories could be summarized as (1) `stray animal, loose`, (2) `stray animal`, contained, (3) `animal surrender`.

```
                Stray Animal |      4,102        0.57       83.25
          Stray Animal Cntnd |        118        0.02       83.27
                   Stray Cat |      1,623        0.22       83.49
          Stray Dog At Large |      9,036        1.25       84.75
         Stray Dog Cntnd-ACC |      1,416        0.20       84.94
         Stray Dog Contained |        939        0.13       85.07
               Surrender Cat |         18        0.00       85.84
               Surrender Dog |         23        0.00       85.84
               Surrender Pet |        151        0.02       85.86
```

```{block, type = "rmdwarning"}
**For projects using a non-standard data set:**
You want to follow the same general process as above. You should have point data, though they may come as `.csv` or `.shp` data. If they were obtained from a geodatabase, export them to `.shp` and then import them into `R`. If you need to geocode the data (i.e. you have address or city identifiers but no spatial data for them), see Chris to discuss this process.
```
