# Research Note

```{block, type = "rmdgoal"}
**Goal:** Create a short paper in the style of a "research note"
```

```{block, type = "rmdpersonnel"}
**Personnel:** This vignette should be completed **only** by students in SOC 5650. 
```

```{block, type = "rmddue"}
**Required Due Date, Draft (WP-G2):** Meeting 4-3 (April 11th)

**Required Due Date, Peer Reviews (WP-G3):** April 20th

**Required Due Date, Final Paper:** May 16th
```

```{block, type = "rmddeliver"}
**Deliverables:** A `.pdf` article manuscript
```

## Overview
Your paper should include the level of detail you believe necessary to introduce the literature on your topic. Literature reviews should *synthesize* articles, not summarize them. Look at the way the articles you find handle this task, and model your papers on their approaches.

As for the rest of your paper, introductions and conclusions should be no more than 2-3 paragraphs in length. The data and methods section should provide clear, concise descriptions of the analytic process you used to gather data and perform your analyses. You should provide links to your StoryMap and your GitHub repository, and discuss how these contribute to the reproducibility and accessibility of your work in a paragraph in the data and methods section as well. The results and discussions sections should economically summarize your findings and the importance you attach to them. 

I strongly recommend checking out [Dr. Jessica Calarco's guide for writing academic papers](http://www.jessicacalarco.com/teaching-resources). It is aimed at qualitative work, but its tips on abstracts, introductions, and discussion/conclusion sections.

I have provided a sample manuscript (that is *much* longer than your assigned paper) to give you a sense of the formatting required for this assignment. It is available on Canvas.

## Outline
Your paper should following these general formatting guidelines:

  - Title page (title, author details including name, degree, affiliation)
  - Abstract page (title, 200 words maximum length for the abstract itself)
  - Main body (title, 2,000 words approximate length)
      - Introduction
      - Background and Literature Review
      - Data and Methods
      - Results
      - Discussion
      - Conclusion
  - End notes
  - Bibliography/works cited
  - Tables (optional)
  - Figure captions
  - Figures (one per page)

## Formatting
Your paper should use the following formatting guidelines:

  - Times New Roman font
  - 12 point font
  - Double spacing
  - 1" margins on top, bottom and sides
  - Other formatting should follow ASA or APA Style Guide manuscript formatting guidelines. You can find more details on [ASA](https://owl.english.purdue.edu/owl/resource/583/01/) and [APA](https://owl.english.purdue.edu/owl/resource/560/01/) using Purdue University's library website.
  - Your paper should be approximately 2,000 words (not including end notes or your works cited section)
  - In-text citations are required. Citations are necessary for both direct quotes and for paraphrased material (ideas that are not yours but are in your own words). In addition to in-text citations, a bibliography must be attached for all material. The bibliography should be on a separate page and does not count towards your page total. The type of citation format that you use in this class should follow either the ASA or APA Style Guide. You can find more details on [ASA](https://owl.english.purdue.edu/owl/resource/583/01/) and [APA](https://owl.english.purdue.edu/owl/resource/560/01/) using Purdue University's library website.
  
## Tables and Figures
You should produce a **minimum** of three static maps using `R` or ArcGIS Pro to accompany your manuscript. You should refer to them in the body text on their own line like so:

```
<<<<< FIGURE 1 ABOUT HERE >>>>>
```

These should be based on the same data you use to create your StoryMap web maps. 

If you want, you can also include one or more tables for your manuscript, but this is **optional**.

## Draft Submission
You should have all required elements and draft text at this stage, though the text can be rough (i.e. does not need to be polished at this stage). Open an issue in your final project repository to submit this waypoint, and include a few sentences of self reflection about what you still need to work on before the final submission.

## Peer Reviews
I have provided a sample peer review document on Canvas as well as a sample response to reviewer document. Once you receive access to your partner's paper, you should review it for formatting (using the instructions above), organization, and clarity. You should provide constructive suggestions for how to strengthen the paper. Consider what is present in the introduction, literature review, data and methods, results, discussion, and conclusion - do elements to be changed, added, or removed? You should also consider whether the writing is clear. 

Once you receive your partner's peer review as well as Chris's feedback, you should construct a response to reviewer document that clearly responds to each critique raised in the reviews. I like to copy-and-paste reviews into a Word document and write out my responses to each criticism *before* I actually go about editing the paper. This helps me create a to-do list of tasks to accomplish as part of my editing. Your response to reviewers document should be submitted along with your final paper.

## Final Paper
After constructing your response to reviewers document, you should produce a final version of your paper and submit it as part of the final deadline for the project.

