# (PART) Final Deliverables {-}

# Research Poster Guidelines

```{block, type = "rmdgoal"}
**Goal:** Create a research poster for your final presentation.
```

```{block, type = "rmdpersonnel"}
**Personnel:** This vignette should be completed by **all** students. 
```

```{block, type = "rmdpre"}
**Pre-requisites:** This vignette should be started _after_ Vignette 6's initial completion.
```

```{block, type = "rmdskills"}
**Skills:** Lectures 3 through 6 provide general guidance on color and design.
```

```{block, type = "rmddue"}
**_Draft_ Due Date:** Lecture 13 (April 6^th^) with, at a minimum, your wireframe.

**Final Due Date:** Final Presentations (May 11^th^)
```

```{block, type = "rmddeliver"}
**Deliverables:** An printed poster for the final due date **only**; a `.pdf` of your poster for both the **draft** and **final** due dates.
```

## General Elements
Your poster should contain the following elements:

1.  A title across the top of the poster.

2.  Information about authorship, the course number, and the date of the
    final project presentation session.

3.  Three text boxes:

    *  An introduction box that briefly addresses each of the following
        three questions - what is the Citizen's Service Bureau, what are
        you mapping, and why is it important? This introductory box will
        contain Map 1 (see below).

    *  A data and methods box that describes your data - what sources
        did you obtain data from? What have you done to modify these
        data?

    *  A discussion box that provides some brief discussion of your
        findings - where do you see the issues you found in the
        Citizen's Service Bureau data occurring in St. Louis? Does there
        appear to be overlap with the demographic map you produced?

4.  If possible, a relevant photo that illustrates your topic.

5.  Eight maps:

    *  *Map 1:* A reference map to be included in your introductory box showing St. Louis's location relative to the rest of Missouri.

    *  *Map 2:* A reference map of the City of St. Louis.

    *  *Maps 3 & 4:* Two thematic demographic maps showing data at the Census block group level.

    *  *Map 5:* A thematic map showing the number of CSB incidents for your topic at the block group level.

    *  *Map 6:* A set of small multiples showing the number of incidents for your topic per year at the block group level.
        
    *  *Map 7:* A detailed map of your selected ward showing point locations for CSB incidents for your topic along with local contextual details.

    *  *Map 8:* An inset map showing the location of your specific ward, selected by you because of the high frequency of incidents for your topic there, relative to the rest of the City.

## Creating Your Wire Frame

Using Microsoft PowerPoint or Apple Keynote, create a wire frame that lays out these elements. If you use Microsoft PowerPoint, set your slide size to 44" wide by 40" tall. If you use Apple Keynote, set your slide size to 3168pt wide by 2880pt tall. Add wire frame boxes and reference text describing each box's dimensions for each element listed above. Export your wire frame as a `.pdf` file.

## Design Instructions

Your poster should follow the dimensions introduced in the prior section. As you complete the design of your poster, give careful thought to the aesthetics of your layout. Use color strategically and in ways that complement the maps you have already designed. Use boxes around content, such as text boxes, strategically as well. Your overall design should be secondary to your data - color choices, text boxes, and font choices should not distract from the core story that your poster tells. Make sure your font choices are legible and easy to read from a distance. Do not use fonts smaller than 20-24 point, depending on the font face itself, and use variation in font size and weight (bold, italic, etc.) to create a visual hierarchy as you would on a map layout itself.

When you export your map images and select accompanying images (such as photographs or, if you wish, a graph), ensure that they are not pixelated when sized to the dimensions available on your wire frame. Use only high quality images on your poster, as low quality or low resolution images are hard to read and detract from your overall design. For maps and images that you did not directly produce (such as the demographic maps and reference maps by your group members, provide appropriate attribution). Be sure to label each map with a title and to place legends near the map they refer to.

Refer back to Brewer (2015) to advice on design more generally, and check out the University of Buffalo Library's [guide to poster design](http://research.lib.buffalo.edu/poster-presentations). SLU's [Instructional Media
Center](https://www.slu.edu/its/services-and-products/multimedia-services-and-computer-labs/instructional-media-center) also has some [resources](https://sites.google.com/a/slu.edu/creating-posters/?pli=1) on poster design.

## Poster Printing

Your poster can be printed in the Library's Academic Technology commons area, which is located on the first floor near the West Pine entrance. If you design your poster in Apple Keynote, be sure to arrive with a copy of you poster exported as a `.pdf` file.

During finals, the Library has extended hours that should allow you to get your poster printed in the evening if you are not regularly on campus during the day. They get busy during this period, however, so be sure to give yourself sufficient lead time to get your poster printed. Arriving at the Library just before the poster presentation session is **not** recommended; we suggest getting your poster printed a day or two before to reduce the likelihood of any delays and give you time to address any issues.

Note that you will need to pay using funds from your Billiken Bucks bucks account. The cost of your poster should be approximately thirty dollars. This is *significantly* cheaper than having a poster printed at a store that offers printing services, like FedEx.

## Poster Presentation Session

During our assigned final exam period, we will host a mini-research conference in the Busch Student Center, Room 173. For Spring 2019, this will be on **May 13^th^** from **4:00pm to 5:50pm**. Please arrive ten minutes before the beginning of our poster session to set up your poster. We will provide easels and foam core boards to mount your poster onto. Come prepared to speak for three to four minutes about your findings.
