# (PART) Deliverables {-}

# ArcGIS StoryMap

```{block, type = "rmdgoal"}
**Goal:** Create an ArcGIS StoryMap featuring your maps, media, and narrative content
```

```{block, type = "rmdpersonnel"}
**Personnel:** This vignette should be completed by **all** students. 
```

```{block, type = "rmdskills"}
**Skills:** This vignette requires skills from Module 4
```

```{block, type = "rmddue"}
**Required Due Date, Draft (WP-6):** Meeting 4-4 (April 25th)

**Required Due Date, Final StoryMap:** May 16th
```

```{block, type = "rmddeliver"}
**Deliverables:** An ArcGIS StoryMap, linked to in a GitHub issue
```

## Web Maps
You will need to create a **minimum** of five web maps to place into your StoryMap. Data for each of your five months should be uploaded to the `Content` section of ArcGIS Online and mapped using ArcGIS Online as well. The minimum set of web maps includes:

  1. A map of your main topic displayed as point data
  2. A map of your main topic aggregated to census tracts (or your selected areal unit)
  3. Two maps showing relevant demographic data for the same census tracts (or your selected areal unit)
  4. A detailed map showing a smaller slice of your data for a specific region along with some additional contextual spatial data.
  
Map four in particular should utilize other data sources that you have accumulated. For students focusing on the City of St. Louis, I recommend focusing on a particular neighborhood or ward where a large number of points are located for your main topic. 

```{block, type = "rmdwarning"}
**For projects using a non-standard data set:**
For students who are not focusing on St. Louis, your will need to select a smaller geography (such as a specific county or state) to focus on.
```

## StoryMap
Once you have your web maps created, you should create a StoryMap to feature these data. Your StoryMap should use a **minimum** of two different mapping techniques (e.g. single maps, sliders, and sidecars) to display your spatial data. The StoryMap should also contain approximately 800 to 1,000 total words of narrative text that provide some background, describe the maps, and draw some basic, descriptive conclusions. You will want to use headings and subheadings to organize this content in a logical, linear fashion. You should embed at least two photos, videos, or other relevant media that add detail and visual richness to your StoryMap. 

At the bottom of your StoryMap, provide a short description of where your data came from, relevant links (including to the original sources for both of your embedded media), and a [Creative Commons license](https://creativecommons.org/share-your-work/). 

