# (PART) Initial Steps {-}

# Topic & Data Selection

```{block, type = "rmdgoal"}
**Goal:** Identify a data set and appropriate variables of interest.
```

```{block, type = "rmdpersonnel"}
**Personnel:** This vignette should be completed by **all** students.
```

```{block, type = "rmdpre"}
**Pre-requisties:** There are no pre-requisites for this vignette.
```

```{block, type = "rmdskills"}
**Skills:** There are no course-specific skills for this vignette.
```

```{block, type = "rmddue"}
**Required Due Date:** Lecture 4 (February 4^th^)
```

```{block, type = "rmddeliver"}
**Deliverables:** A [short memo](/the-memo.html) detailing your data and the specific topic you'll be exploring.
```

## Crafting a Research Question
The process of conducting a research project starts with defining a research question to explore. For many students, this can be daunting. Yale University Sociology's <a href="https://sociology.yale.edu/sites/default/files/files/Writing_Sociology_Senior_Thesis_Guide_Final_Latest_Update.pdf" target="_blank">Handbook for Undergraduate Thesis research</a> usefully breaks down the types of questions sociologists answer into three broad categories. I've provided these three categories below along with some sample research questions on undocumented immigration:

* "Questions about the meaning of certain activities, practices, or experiences for particular social groups."
    - "How do classmates respond when a student discloses that they are an undocumented immigrant?"
    - "How does participation in an immigrant advocacy group effect undocumented immigrants?"
    - "How does disclosing undocumented status change the treatment of immigrants in social services settings?"
* "Questions about the ways that identification with larger social categories – race, ethnicity, religion, political identification, gender – affect aspects of social life."
    - "What is the relationship between political conservatism and beliefs about immigration?"
    - "How do views of immigration vary based on gender identity?"
    - "What is the relationship between religiosity and support for undocumented immigrants?"
* "Questions about the influence of particular variables on other variables or outcomes, including questions that compare groups and track trends across a broader scale."
    - "What is the relationship between levels of education and employment for undocumented immigrants?"
    - "How does racial segregation impact the outcomes of undocumented immigrants in cities?"
    - "What is the effect of DREAMer status on educational attainment?"

Each student should think about the overarching category they want to conduct research in. Like the research process as a whole (see "[Data Analysis is not Linear]"), you may find that crafting a research question is an iterative process. You'll start with a broad topic, make a first attempt at narrowing it down, and then subsequently update the question as you find some related sources (and, if you are in SOC 5050, conduct a full-fledged literature review). Research questions for this course will be necessarily *descriptive* - "what is the spatial distribution of *x*?"

## The Crime Data

## The Citizens' Service Bureau Data

## Another Data Set
If the crime and non-emergency call data do not interest you, you are welcome to choose a topic of your own provided you can find appropriate data.

### Characteristics of an Appropriate Data Set
Data sets for your final project will have a number of salient characteristics: 

1. They should be *spatial* data.
2. They should numerous - there should be at least several hundred observations that vary over space and, ideally, over time as well. Several thousand observations will be ideal.
3. They should be point data (or have the ability to be mapped as point data). Examples would be cities throughout a country or a region, resturant locations across a city, state, or province, and crime scene locations.
4. They should be able to be aggregated up to some sort of higher order construct. Think about how resturant locations could be aggregated up to neighborhoods, municipalities, or counties.

### Other Considerations
For those of you enrolled in SOC 5050, there are a few other considerations to take into account. If you have already identified a possible thesis topic, pick a data set that is either a possible candidate for inclusion in your thesis *or*, at the very least, is conceptually related. You want to maximize the impact that your coursework has, so even if you are not sure whether or not the data set itself will be helpful, picking something in the same topic area will mean that your literature search can be put to use on future assignments (such as in your Research Methods course).

### Finding an Appropriate Data Set
In general, you are free to use any resource to identify a suitable data set that meets the above criteria with a couple of caveats:

1. There is **not** time for you to collect your own data.
2. There is **not** time for you to go through the IRB process to gain access to confidential data (either data that is not publicly available or data collected by a thesis adviser or other faculty member).
3. The data you use should be licensed for re-use (it cannot be proprietary or otherwise restrictively licensed).
4. The data should be well documented - you want to be very sure what each variable represents. If there is no code book or documentation, the data set is probably not appropriate for this project. *See Chris if you have questions about this.*

## The Memo
Once you have completed **all** of the steps for identifying a suitable data set, outcome variable, and possible independent variables, you should create a new [issue](https://help.github.com/articles/about-issues/) on your **final project repository**. In your issue: 

1. State what your research question is, 
2. identify the data you are using to address that question, 
3. and the main category within the data you would like to map.

Once you have your memo drafted, open an issue in your *final project* repository and [assign it](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) to Chris for review.
