# Maps 2-4 - General Maps

```{block, type = "rmdgoal"}
**Goal:** Create an a reference map of your site as well as both demographic maps.
```

```{block, type = "rmdpersonnel"}
**Personnel:** This vignette should be completed by **all** students. 
```

```{block, type = "rmdpre"}
**Pre-requisites:** This vignette should be started _after_ Vignette 6's initial completion.
```

```{block, type = "rmdskills"}
**Skills:** Lectures 3 through 6
```

```{block, type = "rmddue"}
**_Suggested_ Due Date:** Lecture 13 (April 6^th^)
```

```{block, type = "rmddeliver"}
**Deliverables:** An output image file for each map.
```

## Map 2 - City Reference Map
This map should give a basic overview of the City of St. Louis using data obtained in vignette 6. Since many of your maps will be thematic maps that have limited spatial context, this map will be critical for allowing your audience to interpret where patterns on the thematic maps are located in relation to well-known landmarks.

The map should include data on the various types of streets (interstates, state highways, and surface streets), hydrology (major bodies of water), major areas of greenspace (parks, cemeteries, and other recreation sites), and the border between Missouri and Illinois. Be sure to include street data that spans the entire width of the Mississippi River to avoid the "bridge to nowhere" phenomenon.

**Design Guidelines:** There should not be any ground layers outside of the extent of the City boundary and the Mississippi River data. Appropriately label features to help provide additional context for your audience. When you export the map image, make sure that the map view is designed to limit Missouri's boundary from appearing to far above and below the City boundary. This map should be exported to match the background color of your poster at 500dpi.

```{block, type = "rmdwarning"}
**For projects using a non-standard data set:**
This map should focus on your research site. For example, a project for Japan would want to show the country as a whole (perhaps without minor outlying islands).
```

## Maps 3 and 4 - Demographic Maps
These maps should each feature one demographic variable based on the data you created in vignette 5.

**Design Guidelines:** It should use a 5-class color ramp from Color Brewer to map *appropriately normalized* demographic data at the Census block group level. It should not have other layers outside of the thematic data. The seclected color ramps should be different but should not clash. This map should be accompanied by a legend and should be exported to match the background color of your poster at 500dpi.
